name: Create App
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install NodeJS
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Python script
        env:
          SINO_USER: ${{ secrets.SINO_USER }}
        run: |
          echo "Start"
          pwd
          python run.py
      - name: Build app
        run: |
          cd app
          npm install
          npm run build-gh
          cp ../data.json dist/assets/data.json
      - name: gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist/
          clean: true  # Set to true if you want to remove old files
